$(document).ready(function(){
    $('.list').click(function(){
        const value = $(this).attr('data-filter');
        if(value == 'All'){
            $('.itemBox').show(1000);
        }else{
            $('.itemBox').not('.'+value).hide(1000);
            $('.itemBox').filter('.'+value).show(1000);
        }
    });
    //add active class and Remove Active Class
    $('.list').click(function(){
        $(this).addClass('active').siblings().removeClass('active');
    });

    $('.slider-wrapper').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        nav:false,
        dots:false,
        autoplay:true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1,
            },
            600:{
                items:1,
            },
            1000:{
                items:1,
            }
        }
    })
    $('.team-slider').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        nav:false,
        dots:false,
        autoplay:true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
    })
    $('.fachilitis-slider').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        nav:false,
        dots:true,
        autoplay:true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })
    $('.testiminials').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        nav:false,
        dots:true,
        autoplay:true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
    })
    $('.partner-slider').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        nav:false,
        dots:false,
        autoplay:true,
        autoplayTimeout:1000,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })
});